name: Sync Datasets
on:
  schedule:
    - cron: "0 0 * * *" # This will run the action every day at midnight
  workflow_dispatch:

jobs:
  sync_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm install axios
          npm install googleapis

      - name: Run Sync Script
        run: node sync.js

      - name: Commit and Push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Sync datasets updates"
          git push
