name: Sync Google Sheets Data to Repository

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the action every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow from GitHub UI

jobs:
  sync-data:
    name: Sync Data from Google Sheets
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Sync Script
      run: node sync.js
      env:
        GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}

    - name: Setup Git User
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        
    - name: Commit and Push Changes
      run: |
        git add -A
        git commit -m "Updated datasets from Google Sheets" || echo "No changes to commit"
        git push
